-- ============================================================
-- Hermz & D — Writer field update
-- Generated from omdb_cache.json
-- Run AFTER add_writer_column.sql
-- ============================================================

BEGIN;

UPDATE public.films SET writer = 'Herman J. Mankiewicz, Orson Welles, Roger Q. Denny' WHERE omdb_id = 'tt0033467';
UPDATE public.films SET writer = 'Thomas Keneally, Steven Zaillian' WHERE omdb_id = 'tt0108052';
UPDATE public.films SET writer = 'Boyd Clack' WHERE omdb_id = 'tt0940149';
UPDATE public.films SET writer = 'Baz Luhrmann, Craig Pearce' WHERE omdb_id = 'tt0203009';
UPDATE public.films SET writer = 'Lawrence Kasdan, George Lucas, Philip Kaufman' WHERE omdb_id = 'tt0082971';
UPDATE public.films SET writer = 'Reginald Rose' WHERE omdb_id = 'tt0050083';
UPDATE public.films SET writer = 'Leigh Brackett, Lawrence Kasdan, George Lucas' WHERE omdb_id = 'tt0080684';
UPDATE public.films SET writer = 'George Lucas' WHERE omdb_id = 'tt0076759';
UPDATE public.films SET writer = 'Peter Shaffer, Zdenek Mahler' WHERE omdb_id = 'tt0086879';
UPDATE public.films SET writer = 'Christopher Nolan, Jonathan Nolan' WHERE omdb_id = 'tt0209144';
UPDATE public.films SET writer = 'Daniel Myrick, Eduardo Sánchez, Heather Donahue' WHERE omdb_id = 'tt0185937';
UPDATE public.films SET writer = 'Ethan Coen, Joel Coen' WHERE omdb_id = 'tt0118715';
UPDATE public.films SET writer = 'William Shakespeare, Kenneth Branagh' WHERE omdb_id = 'tt0116477';
UPDATE public.films SET writer = 'Thomas Harris, Ted Tally' WHERE omdb_id = 'tt0102926';
UPDATE public.films SET writer = 'William Shakespeare, Kenneth Branagh' WHERE omdb_id = 'tt0107616';
UPDATE public.films SET writer = 'William Goldman' WHERE omdb_id = 'tt0093779';
UPDATE public.films SET writer = 'Noel Langley, Florence Ryerson, Edgar Allan Woolf' WHERE omdb_id = 'tt0032138';
UPDATE public.films SET writer = 'Lawrence Kasdan, George Lucas' WHERE omdb_id = 'tt0086190';
UPDATE public.films SET writer = 'Randall Wallace' WHERE omdb_id = 'tt0112573';
UPDATE public.films SET writer = 'Ethan Coen, Joel Coen' WHERE omdb_id = 'tt0116282';
UPDATE public.films SET writer = 'Lilly Wachowski, Lana Wachowski' WHERE omdb_id = 'tt0133093';
UPDATE public.films SET writer = 'Billy Wilder, Raymond Chandler, James M. Cain' WHERE omdb_id = 'tt0036775';
UPDATE public.films SET writer = 'Tom Schulman' WHERE omdb_id = 'tt0097165';
UPDATE public.films SET writer = 'William Shakespeare, Kenneth Branagh' WHERE omdb_id = 'tt0097499';
UPDATE public.films SET writer = 'Robert Zemeckis, Bob Gale' WHERE omdb_id = 'tt0088763';
UPDATE public.films SET writer = 'Alejandro Amenábar' WHERE omdb_id = 'tt0230600';
UPDATE public.films SET writer = 'Homer, Ethan Coen, Joel Coen' WHERE omdb_id = 'tt0190590';
UPDATE public.films SET writer = 'Joseph Stefano, Robert Bloch' WHERE omdb_id = 'tt0054215';
UPDATE public.films SET writer = 'Jeffrey Boam, George Lucas, Menno Meyjes' WHERE omdb_id = 'tt0097576';
UPDATE public.films SET writer = 'Andrew Stanton, Rita Hsiao, Doug Chamberlin' WHERE omdb_id = 'tt0120363';
UPDATE public.films SET writer = 'Bob Tzudiker, Noni White' WHERE omdb_id = 'tt0104990';
UPDATE public.films SET writer = 'Quentin Tarantino, Roger Avary' WHERE omdb_id = 'tt0110912';
UPDATE public.films SET writer = 'Christopher Guest, Eugene Levy' WHERE omdb_id = 'tt0118111';
UPDATE public.films SET writer = 'Tim Robbins' WHERE omdb_id = 'tt0150216';
UPDATE public.films SET writer = 'George Clayton Johnson, Jack Golden Russell, Harry Brown' WHERE omdb_id = 'tt0240772';
UPDATE public.films SET writer = 'Jeb Stuart, David Twohy, Roy Huggins' WHERE omdb_id = 'tt0106977';
UPDATE public.films SET writer = 'Joss Whedon, Andrew Stanton, Joel Cohen' WHERE omdb_id = 'tt0114709';
UPDATE public.films SET writer = 'Keith Stahle' WHERE omdb_id = 'tt5852184';
UPDATE public.films SET writer = 'Joel Coen, Ethan Coen' WHERE omdb_id = 'tt0243133';
UPDATE public.films SET writer = 'Winston Groom, Eric Roth' WHERE omdb_id = 'tt0109830';
UPDATE public.films SET writer = 'Jan Sardi, Scott Hicks' WHERE omdb_id = 'tt0117631';
UPDATE public.films SET writer = 'John Hughes' WHERE omdb_id = 'tt0091042';
UPDATE public.films SET writer = 'Melissa Mathison' WHERE omdb_id = 'tt0083866';
UPDATE public.films SET writer = 'Peter Benchley, Carl Gottlieb' WHERE omdb_id = 'tt0073195';
UPDATE public.films SET writer = 'Michael Crichton, David Koepp' WHERE omdb_id = 'tt0107290';
UPDATE public.films SET writer = 'Oliver Parker, William Shakespeare' WHERE omdb_id = 'tt0114057';
UPDATE public.films SET writer = 'Phil Alden Robinson, Lawrence Lasker, Walter F. Parkes' WHERE omdb_id = 'tt0105435';
UPDATE public.films SET writer = 'Dana Olsen' WHERE omdb_id = 'tt0096734';
UPDATE public.films SET writer = 'Charles Chaplin' WHERE omdb_id = 'tt0027977';
UPDATE public.films SET writer = 'Steven Naifeh, Gregory White Smith, Barbara Turner' WHERE omdb_id = 'tt0183659';
UPDATE public.films SET writer = 'Hui-Ling Wang, James Schamus, Kuo Jung Tsai' WHERE omdb_id = 'tt0190332';
UPDATE public.films SET writer = 'William Steig, Ted Elliott, Terry Rossio' WHERE omdb_id = 'tt0126029';
UPDATE public.films SET writer = 'James Cameron, William Wisher' WHERE omdb_id = 'tt0103064';
UPDATE public.films SET writer = 'Bruce Joel Rubin' WHERE omdb_id = 'tt0099653';
UPDATE public.films SET writer = 'Wes Anderson, Owen Wilson' WHERE omdb_id = 'tt0265666';
UPDATE public.films SET writer = 'Clark Gregg, Sarah Kernochan' WHERE omdb_id = 'tt0161081';
UPDATE public.films SET writer = 'Quentin Tarantino, Elmore Leonard' WHERE omdb_id = 'tt0119396';
UPDATE public.films SET writer = 'Jim Garrison, Jim Marrs, Oliver Stone' WHERE omdb_id = 'tt0102138';
UPDATE public.films SET writer = 'Dan Aykroyd, Harold Ramis' WHERE omdb_id = 'tt0087332';
UPDATE public.films SET writer = 'Lowell Cunningham, Ed Solomon' WHERE omdb_id = 'tt0119654';
UPDATE public.films SET writer = 'Diane Thomas' WHERE omdb_id = 'tt0088011';
UPDATE public.films SET writer = 'William Peter Blatty' WHERE omdb_id = 'tt0070047';
UPDATE public.films SET writer = 'Rita Rudner, Martin Bergman' WHERE omdb_id = 'tt0105130';
UPDATE public.films SET writer = 'Steven Spielberg, Hal Barwood, Jerry Belson' WHERE omdb_id = 'tt0075860';
UPDATE public.films SET writer = 'Gene Roddenberry, Jack B. Sowards, Harve Bennett' WHERE omdb_id = 'tt0084726';
UPDATE public.films SET writer = 'James Cameron, David Giler, Walter Hill' WHERE omdb_id = 'tt0090605';
UPDATE public.films SET writer = 'Scott McPherson' WHERE omdb_id = 'tt0116999';
UPDATE public.films SET writer = 'Mark Steven Johnson' WHERE omdb_id = 'tt0113228';
UPDATE public.films SET writer = 'Dean Devlin, Roland Emmerich' WHERE omdb_id = 'tt0116629';
UPDATE public.films SET writer = 'Gene Roddenberry, Leonard Nimoy, Harve Bennett' WHERE omdb_id = 'tt0092007';
UPDATE public.films SET writer = 'Bob Kane, Sam Hamm, Warren Skaaren' WHERE omdb_id = 'tt0096895';
UPDATE public.films SET writer = 'Stephen King, Raynold Gideon, Bruce A. Evans' WHERE omdb_id = 'tt0092005';
UPDATE public.films SET writer = 'Mel Brooks, Thomas Meehan, Ronny Graham' WHERE omdb_id = 'tt0094012';
UPDATE public.films SET writer = 'Gene Roddenberry, Rick Berman, Brannon Braga' WHERE omdb_id = 'tt0117731';
UPDATE public.films SET writer = 'David Mamet' WHERE omdb_id = 'tt0120202';
UPDATE public.films SET writer = 'Christopher Guest, Michael McKean, Harry Shearer' WHERE omdb_id = 'tt0088258';
UPDATE public.films SET writer = 'Kevin Jarre' WHERE omdb_id = 'tt0108358';
UPDATE public.films SET writer = 'Christopher Guest, Eugene Levy' WHERE omdb_id = 'tt0218839';
UPDATE public.films SET writer = 'Jeff Arch, Nora Ephron, David S. Ward' WHERE omdb_id = 'tt0108160';
UPDATE public.films SET writer = 'Willard Huyck, Gloria Katz, George Lucas' WHERE omdb_id = 'tt0087469';
UPDATE public.films SET writer = 'Kenneth Branagh' WHERE omdb_id = 'tt0113403';
UPDATE public.films SET writer = 'Jerry Siegel, Joe Shuster, Mario Puzo' WHERE omdb_id = 'tt0081573';
UPDATE public.films SET writer = 'Michael Kalesniko' WHERE omdb_id = 'tt0207524';
UPDATE public.films SET writer = 'Jerry Zucker, Jim Abrahams, David Zucker' WHERE omdb_id = 'tt0095705';
UPDATE public.films SET writer = 'Frank Waldman, Blake Edwards' WHERE omdb_id = 'tt0075066';
UPDATE public.films SET writer = 'John Landis, Jonathan Lynn, Anthony E. Pratt' WHERE omdb_id = 'tt0088930';
UPDATE public.films SET writer = 'Scott Frank' WHERE omdb_id = 'tt0101669';
UPDATE public.films SET writer = 'Mike Judge' WHERE omdb_id = 'tt0151804';
UPDATE public.films SET writer = 'Ron Clements, John Musker, Ted Elliott' WHERE omdb_id = 'tt0103639';
UPDATE public.films SET writer = 'Michael McDowell, Warren Skaaren, Larry Wilson' WHERE omdb_id = 'tt0094721';
UPDATE public.films SET writer = 'Roderick Thorp, Jeb Stuart, Steven E. de Souza' WHERE omdb_id = 'tt0095016';
UPDATE public.films SET writer = 'Jim Abrahams, David Zucker, Jerry Zucker' WHERE omdb_id = 'tt0080339';
UPDATE public.films SET writer = 'Blake Edwards, William Peter Blatty, Harry Kurnitz' WHERE omdb_id = 'tt0058586';
UPDATE public.films SET writer = 'Brian Doyle-Murray, Harold Ramis, Douglas Kenney' WHERE omdb_id = 'tt0080487';
UPDATE public.films SET writer = 'Tennessee Williams, Oscar Saul' WHERE omdb_id = 'tt0044081';
UPDATE public.films SET writer = 'Mario Puzo, Francis Ford Coppola' WHERE omdb_id = 'tt0068646';
UPDATE public.films SET writer = 'Jane Austen, Emma Thompson' WHERE omdb_id = 'tt0114388';
UPDATE public.films SET writer = 'Stephen King, Frank Darabont' WHERE omdb_id = 'tt0111161';
UPDATE public.films SET writer = 'Robert Rodat' WHERE omdb_id = 'tt0120815';
UPDATE public.films SET writer = 'Woody Allen, Marshall Brickman' WHERE omdb_id = 'tt0075686';
UPDATE public.films SET writer = 'Stanley Kubrick, Terry Southern, Peter George' WHERE omdb_id = 'tt0057012';
UPDATE public.films SET writer = 'Alan Ball' WHERE omdb_id = 'tt0169547';
UPDATE public.films SET writer = 'Aaron Sorkin' WHERE omdb_id = 'tt0104257';
UPDATE public.films SET writer = 'Frances Goodrich, Albert Hackett, Frank Capra' WHERE omdb_id = 'tt0038650';
UPDATE public.films SET writer = 'Paul Thomas Anderson' WHERE omdb_id = 'tt0175880';
UPDATE public.films SET writer = 'Christopher McQuarrie' WHERE omdb_id = 'tt0114814';
UPDATE public.films SET writer = 'Paul Schrader' WHERE omdb_id = 'tt0075314';
UPDATE public.films SET writer = 'Vincenzo Cerami, Roberto Benigni' WHERE omdb_id = 'tt0118799';
UPDATE public.films SET writer = 'John Milius, Francis Ford Coppola, Michael Herr' WHERE omdb_id = 'tt0078788';
UPDATE public.films SET writer = 'Nicholas Pileggi, Martin Scorsese' WHERE omdb_id = 'tt0099685';
UPDATE public.films SET writer = 'Chuck Palahniuk, Jim Uhls' WHERE omdb_id = 'tt0137523';
UPDATE public.films SET writer = 'Christopher Nolan, Jonathan Nolan' WHERE omdb_id = 'tt0209144';
UPDATE public.films SET writer = 'Alvin Sargent, Laura Ziskin, Tom Schulman' WHERE omdb_id = 'tt0103241';
UPDATE public.films SET writer = 'Woody Allen, Douglas McGrath' WHERE omdb_id = 'tt0109348';
UPDATE public.films SET writer = 'Matt Damon, Ben Affleck' WHERE omdb_id = 'tt0119217';
UPDATE public.films SET writer = 'Barry Morrow, Ron Bass' WHERE omdb_id = 'tt0095953';
UPDATE public.films SET writer = 'Robert Duvall' WHERE omdb_id = 'tt0118632';
UPDATE public.films SET writer = 'Barnaby Eaton-Jones' WHERE omdb_id = 'tt37343970';
UPDATE public.films SET writer = 'Billy Bob Thornton' WHERE omdb_id = 'tt0117666';
UPDATE public.films SET writer = 'Wes Anderson, Owen Wilson' WHERE omdb_id = 'tt0128445';
UPDATE public.films SET writer = 'Kazuo Ishiguro, Ruth Prawer Jhabvala' WHERE omdb_id = 'tt0107943';
UPDATE public.films SET writer = 'Neil Simon' WHERE omdb_id = 'tt0076095';
UPDATE public.films SET writer = 'Bret Easton Ellis, Mary Harron, Guinevere Turner' WHERE omdb_id = 'tt0144084';
UPDATE public.films SET writer = 'Andre Dubus, Robert Festinger, Todd Field' WHERE omdb_id = 'tt0247425';
UPDATE public.films SET writer = 'Stanley Kubrick, Anthony Burgess' WHERE omdb_id = 'tt0066921';
UPDATE public.films SET writer = 'James Cameron' WHERE omdb_id = 'tt0096754';
UPDATE public.films SET writer = 'Greg Glienna, Mary Ruth Clarke, Jim Herzfeld' WHERE omdb_id = 'tt0212338';
UPDATE public.films SET writer = 'Michael Tolkin' WHERE omdb_id = 'tt0105151';
UPDATE public.films SET writer = 'Giovanni Arpino, Bo Goldman, Ruggero Maccari' WHERE omdb_id = 'tt0105323';
UPDATE public.films SET writer = 'Neil Simon' WHERE omdb_id = 'tt0063374';
UPDATE public.films SET writer = 'Stanley Kubrick, Frederic Raphael, Arthur Schnitzler' WHERE omdb_id = 'tt0120663';
UPDATE public.films SET writer = 'David Mamet' WHERE omdb_id = 'tt0120176';
UPDATE public.films SET writer = 'Albert Lewin, Oscar Wilde' WHERE omdb_id = 'tt0037988';
UPDATE public.films SET writer = 'David Self, Ernest R. May, Philip D. Zelikow' WHERE omdb_id = 'tt0146309';
UPDATE public.films SET writer = 'Mitch Markowitz, Adrian Cronauer' WHERE omdb_id = 'tt0093105';
UPDATE public.films SET writer = 'Mike Myers' WHERE omdb_id = 'tt0118655';
UPDATE public.films SET writer = 'Ira Levin, Jay Presson Allen' WHERE omdb_id = 'tt0083806';
UPDATE public.films SET writer = 'Dale Launer' WHERE omdb_id = 'tt0104952';
UPDATE public.films SET writer = 'Alec Coppel, Samuel A. Taylor, Pierre Boileau' WHERE omdb_id = 'tt0052357';
UPDATE public.films SET writer = 'Mike Myers, Michael McCullers' WHERE omdb_id = 'tt0145660';
UPDATE public.films SET writer = 'Nick Hornby, D.V. DeVincentis, Steve Pink' WHERE omdb_id = 'tt0146882';
UPDATE public.films SET writer = 'John Hughes' WHERE omdb_id = 'tt0093748';
UPDATE public.films SET writer = 'Vincent Gallo, Alison Bagnall' WHERE omdb_id = 'tt0118789';
UPDATE public.films SET writer = 'Stanley Kubrick, Arthur C. Clarke' WHERE omdb_id = 'tt0062622';
UPDATE public.films SET writer = 'Angelo Pizzo' WHERE omdb_id = 'tt0091217';
UPDATE public.films SET writer = 'Steve Martin, Carl Gottlieb, Michael Elias' WHERE omdb_id = 'tt0079367';
UPDATE public.films SET writer = 'Frances Marion, Walter Newman' WHERE omdb_id = 'tt0078950';
UPDATE public.films SET writer = 'Jean C. Havez, Joseph A. Mitchell, Clyde Bruckman' WHERE omdb_id = 'tt0015324';
UPDATE public.films SET writer = 'Richard Matheson' WHERE omdb_id = 'tt0081534';
UPDATE public.films SET writer = 'Gregory McDonald, Andrew Bergman, Phil Alden Robinson' WHERE omdb_id = 'tt0089155';
UPDATE public.films SET writer = 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens' WHERE omdb_id = 'tt0167260';
UPDATE public.films SET writer = 'Robert Rodat' WHERE omdb_id = 'tt0120815';
UPDATE public.films SET writer = 'Rex Pickett, Alexander Payne, Jim Taylor' WHERE omdb_id = 'tt0375063';
UPDATE public.films SET writer = 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens' WHERE omdb_id = 'tt0167261';
UPDATE public.films SET writer = 'Bob Kane, David S. Goyer, Christopher Nolan' WHERE omdb_id = 'tt0372784';
UPDATE public.films SET writer = 'Jonathan Nolan, Christopher Nolan, Christopher Priest' WHERE omdb_id = 'tt0482571';
UPDATE public.films SET writer = 'Ernest Lehman' WHERE omdb_id = 'tt0053125';
UPDATE public.films SET writer = 'Benedict Fitzgerald, Mel Gibson' WHERE omdb_id = 'tt0335345';
UPDATE public.films SET writer = 'Charlie Kaufman, Michel Gondry, Pierre Bismuth' WHERE omdb_id = 'tt0338013';
UPDATE public.films SET writer = 'Bill Condon, Bob Fosse, Fred Ebb' WHERE omdb_id = 'tt0299658';
UPDATE public.films SET writer = 'M. Night Shyamalan' WHERE omdb_id = 'tt0167404';
UPDATE public.films SET writer = 'Ehren Kruger, Kôji Suzuki, Hiroshi Takahashi' WHERE omdb_id = 'tt0298130';
UPDATE public.films SET writer = 'David Franzoni, John Logan, William Nicholson' WHERE omdb_id = 'tt0172495';
UPDATE public.films SET writer = 'John Logan, Richard Ben Cramer, Thomas Lennon' WHERE omdb_id = 'tt0120801';
UPDATE public.films SET writer = 'Judd Apatow, Steve Carell' WHERE omdb_id = 'tt0405422';
UPDATE public.films SET writer = 'J.K. Rowling, Steve Kloves' WHERE omdb_id = 'tt0304141';
UPDATE public.films SET writer = 'Frank Waldman, Blake Edwards' WHERE omdb_id = 'tt0075066';
UPDATE public.films SET writer = 'Brad Bird' WHERE omdb_id = 'tt0317705';
UPDATE public.films SET writer = 'Washington Irving, Kevin Yagher, Andrew Kevin Walker' WHERE omdb_id = 'tt0162661';
UPDATE public.films SET writer = 'Frank Miller, Robert Rodriguez' WHERE omdb_id = 'tt0401792';
UPDATE public.films SET writer = 'Umberto Eco, Andrew Birkin, Gérard Brach' WHERE omdb_id = 'tt0091605';
UPDATE public.films SET writer = 'Joel Coen, Ethan Coen, William Rose' WHERE omdb_id = 'tt0335245';
UPDATE public.films SET writer = 'Zach Braff' WHERE omdb_id = 'tt0333766';
UPDATE public.films SET writer = 'Irene Mecchi, Jonathan Roberts, Linda Woolverton' WHERE omdb_id = 'tt0110357';
UPDATE public.films SET writer = 'Zack Snyder, Kurt Johnstad, Michael B. Gordon' WHERE omdb_id = 'tt0416449';
UPDATE public.films SET writer = 'Neal Purvis, Robert Wade, Paul Haggis' WHERE omdb_id = 'tt0381061';
UPDATE public.films SET writer = 'Jared Hess, Jerusha Hess' WHERE omdb_id = 'tt0374900';
UPDATE public.films SET writer = 'Steve Kloves, J.K. Rowling' WHERE omdb_id = 'tt0330373';
UPDATE public.films SET writer = 'Ann Peacock, Andrew Adamson, Christopher Markus' WHERE omdb_id = 'tt0363771';
UPDATE public.films SET writer = 'Robert Ludlum, Tony Gilroy' WHERE omdb_id = 'tt0372183';
UPDATE public.films SET writer = 'Michael Dougherty, Dan Harris, Bryan Singer' WHERE omdb_id = 'tt0348150';
UPDATE public.films SET writer = 'Lawrence Lasker, Walter F. Parkes' WHERE omdb_id = 'tt0086567';
UPDATE public.films SET writer = 'Jesús Alanís, Alexander Castro Santisteban, M. Lopez' WHERE omdb_id = 'tt18351128';
UPDATE public.films SET writer = 'Lilly Wachowski, Lana Wachowski, David Lloyd' WHERE omdb_id = 'tt0434409';
UPDATE public.films SET writer = 'Michael Hirst' WHERE omdb_id = 'tt0127536';
UPDATE public.films SET writer = 'Andrew Stanton, Daniel Gerson, Pete Docter' WHERE omdb_id = 'tt0198781';
UPDATE public.films SET writer = 'M. Night Shyamalan' WHERE omdb_id = 'tt0286106';
UPDATE public.films SET writer = 'M. Night Shyamalan' WHERE omdb_id = 'tt0217869';
UPDATE public.films SET writer = 'Tony Gilroy, William Blake Herron, Robert Ludlum' WHERE omdb_id = 'tt0258463';
UPDATE public.films SET writer = 'Andrew Stanton, Bob Peterson, David Reynolds' WHERE omdb_id = 'tt0266543';
UPDATE public.films SET writer = 'Gene Roddenberry, Leonard Nimoy, Lawrence Konner' WHERE omdb_id = 'tt0102975';
UPDATE public.films SET writer = 'Gene Roddenberry, John Logan, Rick Berman' WHERE omdb_id = 'tt0253754';
UPDATE public.films SET writer = 'Hillary Seitz, Nikolaj Frobenius, Erik Skjoldbjærg' WHERE omdb_id = 'tt0278504';
UPDATE public.films SET writer = 'Andrew Davies, William Shakespeare' WHERE omdb_id = 'tt0275577';
UPDATE public.films SET writer = 'Andrew Niccol' WHERE omdb_id = 'tt0119177';
UPDATE public.films SET writer = 'Christopher Guest, Eugene Levy' WHERE omdb_id = 'tt0310281';
UPDATE public.films SET writer = 'Jeff Maguire' WHERE omdb_id = 'tt0107206';
UPDATE public.films SET writer = 'George Lucas' WHERE omdb_id = 'tt0121766';
UPDATE public.films SET writer = 'Frank Abagnale Jr., Stan Redding, Jeff Nathanson' WHERE omdb_id = 'tt0264464';
UPDATE public.films SET writer = 'Steven Spielberg, Michael Grais, Mark Victor' WHERE omdb_id = 'tt0084516';
UPDATE public.films SET writer = 'Tom Clancy, Donald E. Stewart, Steven Zaillian' WHERE omdb_id = 'tt0109444';
UPDATE public.films SET writer = 'Joanne Harris, Robert Nelson Jacobs' WHERE omdb_id = 'tt0241303';
UPDATE public.films SET writer = 'Paul Thomas Anderson' WHERE omdb_id = 'tt0118749';
UPDATE public.films SET writer = 'Pierre Boulle, Carl Foreman, Michael Wilson' WHERE omdb_id = 'tt0050212';
UPDATE public.films SET writer = 'Stephen King, Frank Darabont' WHERE omdb_id = 'tt0120689';
UPDATE public.films SET writer = 'Patrick Marber' WHERE omdb_id = 'tt0376541';
UPDATE public.films SET writer = 'Todd Field, Tom Perrotta' WHERE omdb_id = 'tt0404203';
UPDATE public.films SET writer = 'Sylvester Stallone' WHERE omdb_id = 'tt0075148';
UPDATE public.films SET writer = 'Vincenzo Cerami, Roberto Benigni' WHERE omdb_id = 'tt0118799';
UPDATE public.films SET writer = 'John Wagner, Vince Locke, Josh Olson' WHERE omdb_id = 'tt0399146';
UPDATE public.films SET writer = 'Dan O''Bannon, Ronald Shusett' WHERE omdb_id = 'tt0078748';
UPDATE public.films SET writer = 'Stirling Silliphant, Wendell Mayes, Paul Gallico' WHERE omdb_id = 'tt0069113';
UPDATE public.films SET writer = 'David Levien, Brian Koppelman' WHERE omdb_id = 'tt0128442';
UPDATE public.films SET writer = 'David Mamet' WHERE omdb_id = 'tt0104348';
UPDATE public.films SET writer = 'Andrew Kevin Walker' WHERE omdb_id = 'tt0114369';
UPDATE public.films SET writer = 'Claude Chabrol, Alvin Sargent, William Broyles Jr.' WHERE omdb_id = 'tt0250797';
UPDATE public.films SET writer = 'Hayao Miyazaki' WHERE omdb_id = 'tt0245429';
UPDATE public.films SET writer = 'Michael Wilson, Rod Serling, Pierre Boulle' WHERE omdb_id = 'tt0063442';
UPDATE public.films SET writer = 'Sylvester Stallone' WHERE omdb_id = 'tt0479143';
UPDATE public.films SET writer = 'Mike White' WHERE omdb_id = 'tt0332379';
UPDATE public.films SET writer = 'David Benioff' WHERE omdb_id = 'tt0307901';
UPDATE public.films SET writer = 'John Grisham, Francis Ford Coppola, Michael Herr' WHERE omdb_id = 'tt0119978';
UPDATE public.films SET writer = 'John Hughes' WHERE omdb_id = 'tt0085995';
UPDATE public.films SET writer = 'Billy Bob Thornton, Tom Epperson' WHERE omdb_id = 'tt0219699';
UPDATE public.films SET writer = 'Philip K. Dick, Ronald Shusett, Dan O''Bannon' WHERE omdb_id = 'tt0100802';
UPDATE public.films SET writer = 'Daniel E. Taylor, Kario Salem, Lem Dobbs' WHERE omdb_id = 'tt0227445';
UPDATE public.films SET writer = 'Graham Chapman, John Cleese, Eric Idle' WHERE omdb_id = 'tt0071853';
UPDATE public.films SET writer = 'Mike Werb, Michael Colleary' WHERE omdb_id = 'tt0119094';
UPDATE public.films SET writer = 'Jonathan Mostow, Sam Montgomery' WHERE omdb_id = 'tt0118771';
UPDATE public.films SET writer = 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens' WHERE omdb_id = 'tt0120737';
UPDATE public.films SET writer = 'Jonathan Nolan, Christopher Nolan, David S. Goyer' WHERE omdb_id = 'tt0468569';
UPDATE public.films SET writer = 'Pete Docter, Ronnie Del Carmen, Meg LeFauve' WHERE omdb_id = 'tt2096673';
UPDATE public.films SET writer = 'Robert Zemeckis, Bob Gale' WHERE omdb_id = 'tt0096874';
UPDATE public.films SET writer = 'Andrew Stanton, Jim Reardon, Pete Docter' WHERE omdb_id = 'tt0910970';
UPDATE public.films SET writer = 'David Seidler' WHERE omdb_id = 'tt1504320';
UPDATE public.films SET writer = 'Christopher Nolan' WHERE omdb_id = 'tt1375666';
UPDATE public.films SET writer = 'Lawrence Kasdan, J.J. Abrams, Michael Arndt' WHERE omdb_id = 'tt2488496';
UPDATE public.films SET writer = 'Robert Zemeckis, Bob Gale' WHERE omdb_id = 'tt0099088';
UPDATE public.films SET writer = 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens' WHERE omdb_id = 'tt0167261';
UPDATE public.films SET writer = 'Joss Whedon, Zak Penn' WHERE omdb_id = 'tt0848228';
UPDATE public.films SET writer = 'Steve Kloves, J.K. Rowling' WHERE omdb_id = 'tt1201607';
UPDATE public.films SET writer = 'Roberto Orci, Alex Kurtzman, Gene Roddenberry' WHERE omdb_id = 'tt0796366';
UPDATE public.films SET writer = 'Melissa Mathison' WHERE omdb_id = 'tt0083866';
UPDATE public.films SET writer = 'Alfonso Cuarón, Timothy J. Sexton, David Arata' WHERE omdb_id = 'tt0206634';
UPDATE public.films SET writer = 'Mark Fergus, Hawk Ostby, Art Marcum' WHERE omdb_id = 'tt0371746';
UPDATE public.films SET writer = 'Buster Keaton, Clyde Bruckman, Al Boasberg' WHERE omdb_id = 'tt0017925';
UPDATE public.films SET writer = 'Neal Purvis, Robert Wade, John Logan' WHERE omdb_id = 'tt1074638';
UPDATE public.films SET writer = 'John Logan, Brian Selznick' WHERE omdb_id = 'tt0970179';
UPDATE public.films SET writer = 'Frederick Knott' WHERE omdb_id = 'tt0046912';
UPDATE public.films SET writer = 'Bob Peterson, Pete Docter, Tom McCarthy' WHERE omdb_id = 'tt1049413';
UPDATE public.films SET writer = 'Alex Kurtzman, Roberto Orci, J.J. Abrams' WHERE omdb_id = 'tt0317919';
UPDATE public.films SET writer = 'Christopher Markus, Stephen McFeely, Joe Simon' WHERE omdb_id = 'tt1843866';
UPDATE public.films SET writer = 'Ashley E. Miller, Zack Stentz, Jane Goldman' WHERE omdb_id = 'tt1270798';
UPDATE public.films SET writer = 'Ian Fleming, Michael France, Jeffrey Caine' WHERE omdb_id = 'tt0113189';
UPDATE public.films SET writer = 'Andrew Dominik, Ron Hansen' WHERE omdb_id = 'tt0443680';
UPDATE public.films SET writer = 'Oren Peli' WHERE omdb_id = 'tt1179904';
UPDATE public.films SET writer = 'Roy Huggins, William Goldman' WHERE omdb_id = 'tt0110478';
UPDATE public.films SET writer = 'Halsted Welles, Michael Brandt, Derek Haas' WHERE omdb_id = 'tt0381849';
UPDATE public.films SET writer = 'Paul Hogan, Brett Hogan' WHERE omdb_id = 'tt0092493';
UPDATE public.films SET writer = 'Stanley Kubrick, Terry Southern, Peter George' WHERE omdb_id = 'tt0057012';
UPDATE public.films SET writer = 'James Ellroy, Brian Helgeland, Curtis Hanson' WHERE omdb_id = 'tt0119488';
UPDATE public.films SET writer = 'Paul Thomas Anderson, Upton Sinclair' WHERE omdb_id = 'tt0469494';
UPDATE public.films SET writer = 'Steven Soderbergh' WHERE omdb_id = 'tt0098724';
UPDATE public.films SET writer = 'John Gatins' WHERE omdb_id = 'tt1907668';
UPDATE public.films SET writer = 'Neil Simon' WHERE omdb_id = 'tt0063374';
UPDATE public.films SET writer = 'Hirobumi Watanabe' WHERE omdb_id = 'tt3379694';
UPDATE public.films SET writer = 'Rhett Reese, Paul Wernick' WHERE omdb_id = 'tt1156398';
UPDATE public.films SET writer = 'Alexander Emmert, Herodotus, Matt Koed' WHERE omdb_id = 'tt0892737';
UPDATE public.films SET writer = 'David S. Ward' WHERE omdb_id = 'tt0070735';
UPDATE public.films SET writer = 'Charles Brackett, Billy Wilder, D.M. Marshman Jr.' WHERE omdb_id = 'tt0043014';
UPDATE public.films SET writer = 'Peter Stone, Marc Behm' WHERE omdb_id = 'tt0056923';
UPDATE public.films SET writer = 'Damien Chazelle' WHERE omdb_id = 'tt3783958';
UPDATE public.films SET writer = 'Christopher Markus, Stephen McFeely, Stan Lee' WHERE omdb_id = 'tt4154756';
UPDATE public.films SET writer = 'Jonathan Nolan, Christopher Nolan' WHERE omdb_id = 'tt0816692';
UPDATE public.films SET writer = 'Christopher Markus, Stephen McFeely, Stan Lee' WHERE omdb_id = 'tt4154796';
UPDATE public.films SET writer = 'Chris Weitz, Tony Gilroy, John Knoll' WHERE omdb_id = 'tt3748528';
UPDATE public.films SET writer = 'Sam Mendes, Krysty Wilson-Cairns' WHERE omdb_id = 'tt8579674';
UPDATE public.films SET writer = 'Tony Gilroy, Scott Z. Burns, George Nolfi' WHERE omdb_id = 'tt0440963';
UPDATE public.films SET writer = 'Stirling Silliphant, Wendell Mayes, Paul Gallico' WHERE omdb_id = 'tt0069113';
UPDATE public.films SET writer = 'Ben Hecht, John Taintor Foote, Alfred Hitchcock' WHERE omdb_id = 'tt0038787';
UPDATE public.films SET writer = 'Raymond Chandler, Czenzi Ormonde, Whitfield Cook' WHERE omdb_id = 'tt0044079';
UPDATE public.films SET writer = 'H.G. Wells, R.C. Sherriff, Preston Sturges' WHERE omdb_id = 'tt0024184';
UPDATE public.films SET writer = 'Steven Spielberg, Tony Kushner' WHERE omdb_id = 'tt14208870';
UPDATE public.films SET writer = 'Steven Levenson, Jonathan Larson' WHERE omdb_id = 'tt8721424';
UPDATE public.films SET writer = 'Bruce Geller, David Koepp, Steven Zaillian' WHERE omdb_id = 'tt0117060';
UPDATE public.films SET writer = 'Michael Bacall, Edgar Wright, Bryan Lee O''Malley' WHERE omdb_id = 'tt0446029';
UPDATE public.films SET writer = 'David Hemingson' WHERE omdb_id = 'tt14849194';
UPDATE public.films SET writer = 'James Cameron, William Wisher' WHERE omdb_id = 'tt0103064';
UPDATE public.films SET writer = 'Mel Brooks, Thomas Meehan, Ronny Graham' WHERE omdb_id = 'tt0094012';
UPDATE public.films SET writer = 'Stefan Zweig, Wes Anderson, Hugo Guinness' WHERE omdb_id = 'tt2278388';
UPDATE public.films SET writer = 'Scott Frank, Jon Cohen, Philip K. Dick' WHERE omdb_id = 'tt0181689';
UPDATE public.films SET writer = 'Deborah Davis, Tony McNamara' WHERE omdb_id = 'tt5083738';
UPDATE public.films SET writer = 'Justine Triet, Arthur Harari' WHERE omdb_id = 'tt17009710';
UPDATE public.films SET writer = 'Danny Rubin, Harold Ramis' WHERE omdb_id = 'tt0107048';
UPDATE public.films SET writer = 'James V. Hart, Michael Goldenberg, Carl Sagan' WHERE omdb_id = 'tt0118884';
UPDATE public.films SET writer = 'Ben Affleck, Aaron Stockard, Dennis Lehane' WHERE omdb_id = 'tt0452623';
UPDATE public.films SET writer = 'Andrew Niccol' WHERE omdb_id = 'tt0120382';
UPDATE public.films SET writer = 'Tom Ford, Austin Wright' WHERE omdb_id = 'tt4550098';
UPDATE public.films SET writer = 'Martin McDonagh' WHERE omdb_id = 'tt11813216';
UPDATE public.films SET writer = 'Guillermo del Toro, Kim Morgan, William Lindsay Gresham' WHERE omdb_id = 'tt7740496';
UPDATE public.films SET writer = 'Gene Roddenberry, Harold Livingston, Alan Dean Foster' WHERE omdb_id = 'tt0079945';
UPDATE public.films SET writer = 'Brian Aldiss, Ian Watson, Steven Spielberg' WHERE omdb_id = 'tt0212720';
UPDATE public.films SET writer = 'Richard Curtis, Jack Barth' WHERE omdb_id = 'tt8079248';
UPDATE public.films SET writer = 'Walon Green, Georges Arnaud, William Friedkin' WHERE omdb_id = 'tt0076740';
UPDATE public.films SET writer = 'Dale Launer, Stanley Shapiro, Paul Henning' WHERE omdb_id = 'tt0095031';
UPDATE public.films SET writer = 'Gregory McDonald, Leon Capetanos' WHERE omdb_id = 'tt0097366';
UPDATE public.films SET writer = 'Jack Bernstein, Tom Shadyac, Jim Carrey' WHERE omdb_id = 'tt0109040';
UPDATE public.films SET writer = 'Thomas Keneally, Steven Zaillian' WHERE omdb_id = 'tt0108052';
UPDATE public.films SET writer = 'Robert Rodat' WHERE omdb_id = 'tt0120815';
UPDATE public.films SET writer = 'George Lucas' WHERE omdb_id = 'tt0076759';
UPDATE public.films SET writer = 'Peter Shaffer, Zdenek Mahler' WHERE omdb_id = 'tt0086879';
UPDATE public.films SET writer = 'Herman J. Mankiewicz, Orson Welles, Roger Q. Denny' WHERE omdb_id = 'tt0033467';
UPDATE public.films SET writer = 'Ethan Coen, Joel Coen' WHERE omdb_id = 'tt0116282';
UPDATE public.films SET writer = 'Noel Langley, Florence Ryerson, Edgar Allan Woolf' WHERE omdb_id = 'tt0032138';
UPDATE public.films SET writer = 'Lawrence Kasdan, George Lucas, Philip Kaufman' WHERE omdb_id = 'tt0082971';
UPDATE public.films SET writer = 'William Shakespeare, Kenneth Branagh' WHERE omdb_id = 'tt0107616';
UPDATE public.films SET writer = 'Quentin Tarantino, Roger Avary' WHERE omdb_id = 'tt0110912';
UPDATE public.films SET writer = 'William Shakespeare, Kenneth Branagh' WHERE omdb_id = 'tt0116477';
UPDATE public.films SET writer = 'Baz Luhrmann, Craig Pearce' WHERE omdb_id = 'tt0203009';
UPDATE public.films SET writer = 'Ethan Coen, Joel Coen' WHERE omdb_id = 'tt0118715';
UPDATE public.films SET writer = 'Lilly Wachowski, Lana Wachowski' WHERE omdb_id = 'tt0133093';
UPDATE public.films SET writer = 'Robert Zemeckis, Bob Gale' WHERE omdb_id = 'tt0088763';
UPDATE public.films SET writer = 'Andrew Stanton, Rita Hsiao, Doug Chamberlin' WHERE omdb_id = 'tt0120363';
UPDATE public.films SET writer = 'Christopher Nolan, Jonathan Nolan' WHERE omdb_id = 'tt0209144';
UPDATE public.films SET writer = 'Joss Whedon, Andrew Stanton, Joel Cohen' WHERE omdb_id = 'tt0114709';
UPDATE public.films SET writer = 'Thomas Harris, Ted Tally' WHERE omdb_id = 'tt0102926';
UPDATE public.films SET writer = 'Reginald Rose' WHERE omdb_id = 'tt0050083';
UPDATE public.films SET writer = 'Leigh Brackett, Lawrence Kasdan, George Lucas' WHERE omdb_id = 'tt0080684';
UPDATE public.films SET writer = 'Homer, Ethan Coen, Joel Coen' WHERE omdb_id = 'tt0190590';
UPDATE public.films SET writer = 'Winston Groom, Eric Roth' WHERE omdb_id = 'tt0109830';
UPDATE public.films SET writer = 'Lawrence Kasdan, George Lucas' WHERE omdb_id = 'tt0086190';
UPDATE public.films SET writer = 'Joseph Stefano, Robert Bloch' WHERE omdb_id = 'tt0054215';
UPDATE public.films SET writer = 'Jeffrey Boam, George Lucas, Menno Meyjes' WHERE omdb_id = 'tt0097576';
UPDATE public.films SET writer = 'Keith Stahle' WHERE omdb_id = 'tt5852184';
UPDATE public.films SET writer = 'Jeb Stuart, David Twohy, Roy Huggins' WHERE omdb_id = 'tt0106977';
UPDATE public.films SET writer = 'Billy Wilder, Raymond Chandler, James M. Cain' WHERE omdb_id = 'tt0036775';
UPDATE public.films SET writer = 'William Goldman' WHERE omdb_id = 'tt0093779';
UPDATE public.films SET writer = 'Tom Schulman' WHERE omdb_id = 'tt0097165';
UPDATE public.films SET writer = 'Oliver Parker, William Shakespeare' WHERE omdb_id = 'tt0114057';
UPDATE public.films SET writer = 'John Hughes' WHERE omdb_id = 'tt0091042';
UPDATE public.films SET writer = 'Christopher Guest, Eugene Levy' WHERE omdb_id = 'tt0118111';
UPDATE public.films SET writer = 'Michael Frayn, Marty Kaplan' WHERE omdb_id = 'tt0105017';
UPDATE public.films SET writer = 'Gene Roddenberry, Jack B. Sowards, Harve Bennett' WHERE omdb_id = 'tt0084726';
UPDATE public.films SET writer = 'Gene Roddenberry, Leonard Nimoy, Harve Bennett' WHERE omdb_id = 'tt0092007';
UPDATE public.films SET writer = 'Kevin Jarre' WHERE omdb_id = 'tt0108358';
UPDATE public.films SET writer = 'Christopher Guest, Michael McKean, Harry Shearer' WHERE omdb_id = 'tt0088258';
UPDATE public.films SET writer = 'William Shakespeare, Kenneth Branagh' WHERE omdb_id = 'tt0182295';
UPDATE public.films SET writer = 'Christopher Guest, Eugene Levy' WHERE omdb_id = 'tt0218839';
UPDATE public.films SET writer = 'Scott Frank' WHERE omdb_id = 'tt0101669';
UPDATE public.films SET writer = 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens' WHERE omdb_id = 'tt0167260';
UPDATE public.films SET writer = 'Charlie Kaufman, Michel Gondry, Pierre Bismuth' WHERE omdb_id = 'tt0338013';
UPDATE public.films SET writer = 'Keaton Gover, Jack Snelling' WHERE omdb_id = 'tt8207486';
UPDATE public.films SET writer = 'Bob Kane, David S. Goyer, Christopher Nolan' WHERE omdb_id = 'tt0372784';
UPDATE public.films SET writer = 'Randall Wallace' WHERE omdb_id = 'tt0112573';
UPDATE public.films SET writer = 'Jonathan Nolan, Christopher Nolan, Christopher Priest' WHERE omdb_id = 'tt0482571';
UPDATE public.films SET writer = 'Frank Miller, Robert Rodriguez' WHERE omdb_id = 'tt0401792';
UPDATE public.films SET writer = 'Jared Hess, Jerusha Hess' WHERE omdb_id = 'tt0374900';
UPDATE public.films SET writer = 'Zach Braff' WHERE omdb_id = 'tt0333766';
UPDATE public.films SET writer = 'Andrew Niccol' WHERE omdb_id = 'tt0119177';
UPDATE public.films SET writer = 'Mike Myers' WHERE omdb_id = 'tt0118655';
UPDATE public.films SET writer = 'M. Night Shyamalan' WHERE omdb_id = 'tt0286106';
UPDATE public.films SET writer = 'Mike Judge' WHERE omdb_id = 'tt0151804';
UPDATE public.films SET writer = 'Greg Glienna, Mary Ruth Clarke, Jim Herzfeld' WHERE omdb_id = 'tt0212338';
UPDATE public.films SET writer = 'Bill Corbett, Kevin Murphy, Michael J. Nelson' WHERE omdb_id = 'tt33397756';
UPDATE public.films SET writer = 'Jerry Siegel, Joe Shuster, Mario Puzo' WHERE omdb_id = 'tt0081573';

COMMIT;
